repository/template.go, repository/template_test.go
- `expandGithubLinks`: expand github links such as `#42` into a markdown URL `[#42](...)`
- `extractMarkdownURLs`: extract urls from markdown: `[title](http://url)` becomes `http://url`
=> feat: new template functions

main.go, repository/git.go, repository/options.go
- `--git-stage-all-changed`, default to `true` to keep the existing behaviour
note that this only takes "changed" files in account: modified files or deleted files. not new files.
- `--git-stage-pattern`: one or more patterns to add glob of files to the index
=> feat: configure which files to stage

.github/workflows/pull-request.yml
fixes
Error: Unable to resolve action `actions-contrib/golangci-lint@v1`, repository not found
uses https://github.com/marketplace/actions/run-golangci-lint instead
=> chore: fix CI linter job

.github/workflows/pull-request.yml, .github/workflows/release.yml, Dockerfile.goreleaser, go.mod
upgrade:
- go to 1.16
- goreleaser to 0.171.0
- golangci-lint to 1.41.1
- alpine base image to 3.14
=> chore: upgrade tools - go, goreleaser, golangci-lint

.github/workflows/unit-tests.yml
ensure we don't run the unit tests twice for PRs (push & pr events)
=> chore: fix github actions unit tests workflow

repository/repository.go
Hello, 
I am using repositories with `.` inside them Example: `github/github.infra`. 
Currently octopilot can not be used inside such repositories. Regexp will not allow it.
This PR will fix this
=> fix: allow using octopilot on repositories with .(dot) inside them

docs/current-version/content/use-cases/detecting-errors-in-scripts.md, main.go
Add the `--fail-on-error` flag so that Octopilot exits with errors when the update fails.
My use case is to easily detect in automation when an updated errored. At the moment, the only way I've found is to parse the output for errors, which is not very reliable :slightly_smiling_face:
=> feat: add a flag to exit with error code when an update fails

update/updater.go, update/updater_test.go
Loosen up `updaterWithValueRegexp` to accept empty values. This allows captured groups to be replaced by empty values, effectively dropping them.
=> fix: allow empty value in updater regex

.github/workflows/static-analysis.yml, .golangci.yml, docs/current-version/content/github/_index.md, go.mod, internal/git/config_test.go, main.go, repository/git.go, repository/git_test.go, repository/github_client.go, repository/options.go, repository/repository.go, repository/template.go, update/exec/exec.go, update/exec/exec_test.go, update/helm/helm.go, update/helm/helm_test.go, update/regex/regex.go, update/regex/regex_test.go, update/sops/sops.go, update/sops/sops_test.go, update/value/file.go, update/yaml/yaml.go, update/yaml/yaml_test.go, update/yq/yq.go, update/yq/yq_test.go
The --github-url flag can be used to operate on repositories hosted on an Enterprise Github server.
See the doc update for more information.
---
Tested on my work GitHub Enterprise Server 3.5.7 and working fine.
=> feat: add flag to support Enterprise GitHub 

action.yml
Hi,
Would you be up for having a GitHub Action for Octopilot? Here is one way to do it. 
An alternative could be to have a sibling repo just for the action, up to you. A third alternative is to let the community own this (although I think that is easier to manage in a trustworthy way from your org).
For implementation details, see the code in this PR, and docs such as:
- https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
=> Create action.yml for GitHub Actions

.github/CODEOWNERS
Description:
This PR adds daily-devops & daily-devexp teams in the CODEOWNERS file
=> chore: add daily-devops & daily-devexp in CODEOWNERS

docs/current-version/content/repos/pull-request.md, main.go, repository/options.go, repository/pull_request.go
Add a flag `--pr-assignees` that lets you **add** assignees to the PR.
This flag is similar to the `--pr-comments`, in that it's always additive and doesn't replace any pre-exisiting assignees from the PR.
Also fixed a minor (copy-paste?) typo in the returned error for addPullRequestComments.
=> feat: allow adding assignees w/ flag --pr-assignees

main.go, repository/repository.go, repository/result.go
This will write the execution results in a JSON format to the specified file. Other tools/scripts may find this useful to provide additional automation.
The schema looks something like:
```json
{
"repos": [
{
"owner": string,
"repo": string,
"error": null (if there were no errors) or string,
"pr": null (if no pull-request was created) or {
"number": int,
"nodeId": string,
"url": string,
}
}
...
]
}
```
#295
=> feat: add flag --output-results

repository/discover_from_query.go
with the addition of search code repositories, an issue was introduced:
The repos from previous page were always overriden by the current page, until the latest one.
=> fix(discover-from-query): don't only take repos from last page

main.go, repository/result.go, repository/strategy_append.go, repository/strategy_reset.go
I've put it as a feature because it changes the behavior of octopilot
Let's take as example a repository where the PR is unrevised (the PR already exist, not yet merged and doesn't need new update)
```
INFO[0001] Updates finished                              repositories-count=1
INFO[0001] Update summary (Unrevised)                    unrevised-repository-count=1
INFO[0001] Update summary (Unrevised)                    unrevised-repository-pr-url="https://github.com/xxx/yyy/pull/777"
```
Let's take as example a repository where the PR is created / updated by octopilot
```
INFO[0001] Updates finished                            repositories-count=1
INFO[0001] Update summary (Updated)                    updated-repository-count=1
INFO[0001] Update summary (Updated) …
```
=> feat: improve the display of repositories pr url at the end

repository/commit.go, repository/commit_test.go, repository/git.go, repository/repository.go, repository/strategy.go, repository/strategy_append.go, repository/strategy_recreate.go, repository/strategy_reset.go
The goal of this PR is to refactor the implementation of the strategies to move from an interface with an implementation dedicated to each strategy to a generic strategy whose behaviour is defined according to its options.
This refactoring should reduces the code duplication and ease maintenance and the addition of new feature.
Note: I tried to create unit commits to make it easier to review pull request commit by commit.
=> refactor: refactoring introducing a single generic strategy

docs/current-version/content/repos/commit.md, main.go, repository/git.go, repository/options.go, repository/strategy.go
- When set, it will recursively fetch all submodules.
- If any submodule uses a SSH URL (i.e. `git@github.com:ORG/REPO.git`), it will be replaced with a HTTPS one (i.e. `https://github.com/ORG/REPO.git`) so that token authentication can be used to clone private repositories.
- Any public Git repository should work (i.e. those not hosted on Github).
=> add flag to initialize submodules --git-recurse-submodules

docs/current-version/content/github/_index.md
The documentation incorrectly states the `--github-auth-token` flag should be used to change github auth type, when the correct flag is `--github-auth-method`.
=> docs: github auth method flag instead of token

.golangci.yml, repository/git.go, repository/pull_request.go, repository/utils.go
Fixing a few things:
- Use Github REST API to create Git trees & commits. This let's us update submodules commits too. It will still lead to a "verified" commit. For example, to update a submodule, run:
```
octopilot ... --git-recurse-submodules --update 'exec(cmd=git,args=checkout xxxxxx,path=/submodule-path)'
```
- Reset strategy did not actually work. It would just close the PR after the force-push.
- Also the recurse submodule init hack was not substituting the URL correctly
#348
=> fix: submodule updates & reset strategy w/ Github App

internal/git/config.go, internal/git/config_test.go
The eariler approach assumed the domain would be `github.com` and hence did not work for SSH URLs of GitHub Enterprise Servers.
re #164
=> fix: use more generic logic to normalise repository URL
